
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA CONNECT DIV EQUAL EXP LPAREN MINUS NUMBER PLUS RPAREN STRING TIMES VARIABLEassignment : VARIABLE EQUAL expressionassignment : expressionassignment : VARIABLE EQUAL flowflow : VARIABLE CONNECT flow_functionsflow_functions : flow_function_call CONNECT flow_functionsflow_functions : flow_function_callflow_function_call : VARIABLE LPAREN params RPARENexpression : expression PLUS termexpression : expression MINUS termexpression : term \n                      | stringstring : STRINGterm : exponentterm : term TIMES exponentterm : term DIV exponentexponent : factorexponent : factor EXP factorfactor : NUMBERfactor : VARIABLEfactor : LPAREN expression RPARENfactor : function_callfunction_call : VARIABLE LPAREN RPARENfunction_call : VARIABLE LPAREN params RPARENparams : params COMMA expression \n                  | expression'
    
_lr_action_items = {'VARIABLE':([0,10,12,13,14,15,16,17,18,33,35,40,41,],[2,20,21,20,20,20,20,20,20,36,20,20,36,]),'STRING':([0,10,12,13,35,40,],[7,7,7,7,7,7,]),'NUMBER':([0,10,12,13,14,15,16,17,18,35,40,],[9,9,9,9,9,9,9,9,9,9,9,]),'LPAREN':([0,2,10,12,13,14,15,16,17,18,20,21,35,36,40,],[10,13,10,10,10,10,10,10,10,10,13,13,10,40,10,]),'$end':([1,2,3,4,5,6,7,8,9,11,20,21,22,23,24,27,28,29,30,31,32,34,37,38,43,44,],[0,-19,-2,-10,-11,-13,-12,-16,-18,-21,-19,-19,-1,-3,-22,-8,-9,-14,-15,-17,-20,-23,-4,-6,-5,-7,]),'EQUAL':([2,],[12,]),'EXP':([2,8,9,11,20,21,24,32,34,],[-19,18,-18,-21,-19,-19,-22,-20,-23,]),'TIMES':([2,4,6,8,9,11,20,21,24,27,28,29,30,31,32,34,],[-19,16,-13,-16,-18,-21,-19,-19,-22,16,16,-14,-15,-17,-20,-23,]),'DIV':([2,4,6,8,9,11,20,21,24,27,28,29,30,31,32,34,],[-19,17,-13,-16,-18,-21,-19,-19,-22,17,17,-14,-15,-17,-20,-23,]),'PLUS':([2,3,4,5,6,7,8,9,11,19,20,21,22,24,26,27,28,29,30,31,32,34,39,],[-19,14,-10,-11,-13,-12,-16,-18,-21,14,-19,-19,14,-22,14,-8,-9,-14,-15,-17,-20,-23,14,]),'MINUS':([2,3,4,5,6,7,8,9,11,19,20,21,22,24,26,27,28,29,30,31,32,34,39,],[-19,15,-10,-11,-13,-12,-16,-18,-21,15,-19,-19,15,-22,15,-8,-9,-14,-15,-17,-20,-23,15,]),'RPAREN':([4,5,6,7,8,9,11,13,19,20,24,25,26,27,28,29,30,31,32,34,39,42,],[-10,-11,-13,-12,-16,-18,-21,24,32,-19,-22,34,-25,-8,-9,-14,-15,-17,-20,-23,-24,44,]),'COMMA':([4,5,6,7,8,9,11,20,24,25,26,27,28,29,30,31,32,34,39,42,],[-10,-11,-13,-12,-16,-18,-21,-19,-22,35,-25,-8,-9,-14,-15,-17,-20,-23,-24,35,]),'CONNECT':([21,38,44,],[33,41,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'assignment':([0,],[1,]),'expression':([0,10,12,13,35,40,],[3,19,22,26,39,26,]),'term':([0,10,12,13,14,15,35,40,],[4,4,4,4,27,28,4,4,]),'string':([0,10,12,13,35,40,],[5,5,5,5,5,5,]),'exponent':([0,10,12,13,14,15,16,17,35,40,],[6,6,6,6,6,6,29,30,6,6,]),'factor':([0,10,12,13,14,15,16,17,18,35,40,],[8,8,8,8,8,8,8,8,31,8,8,]),'function_call':([0,10,12,13,14,15,16,17,18,35,40,],[11,11,11,11,11,11,11,11,11,11,11,]),'flow':([12,],[23,]),'params':([13,40,],[25,42,]),'flow_functions':([33,41,],[37,43,]),'flow_function_call':([33,41,],[38,38,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> assignment","S'",1,None,None,None),
  ('assignment -> VARIABLE EQUAL expression','assignment',3,'p_assignment_assign','translate.py',123),
  ('assignment -> expression','assignment',1,'p_assignment_expression','translate.py',131),
  ('assignment -> VARIABLE EQUAL flow','assignment',3,'p_assignment_flow','translate.py',135),
  ('flow -> VARIABLE CONNECT flow_functions','flow',3,'p_flow','translate.py',143),
  ('flow_functions -> flow_function_call CONNECT flow_functions','flow_functions',3,'p_flow_functions','translate.py',155),
  ('flow_functions -> flow_function_call','flow_functions',1,'p_flow_functions_alone','translate.py',165),
  ('flow_function_call -> VARIABLE LPAREN params RPAREN','flow_function_call',4,'p_flow_function_call','translate.py',169),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','translate.py',178),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','translate.py',185),
  ('expression -> term','expression',1,'p_expression_term','translate.py',192),
  ('expression -> string','expression',1,'p_expression_term','translate.py',193),
  ('string -> STRING','string',1,'p_string_def','translate.py',197),
  ('term -> exponent','term',1,'p_term_exponent','translate.py',201),
  ('term -> term TIMES exponent','term',3,'p_term_times','translate.py',205),
  ('term -> term DIV exponent','term',3,'p_term_div','translate.py',212),
  ('exponent -> factor','exponent',1,'p_exponent_factor','translate.py',219),
  ('exponent -> factor EXP factor','exponent',3,'p_exponent_exp','translate.py',223),
  ('factor -> NUMBER','factor',1,'p_factor_number','translate.py',230),
  ('factor -> VARIABLE','factor',1,'p_factor_variable','translate.py',234),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expression','translate.py',238),
  ('factor -> function_call','factor',1,'p_factor_function_call','translate.py',244),
  ('function_call -> VARIABLE LPAREN RPAREN','function_call',3,'p_function_call_no_params','translate.py',248),
  ('function_call -> VARIABLE LPAREN params RPAREN','function_call',4,'p_function_call_params','translate.py',252),
  ('params -> params COMMA expression','params',3,'p_params','translate.py',259),
  ('params -> expression','params',1,'p_params','translate.py',260),
]
